# Generated by Django 3.0 on 2019-12-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store', models.IntegerField(choices=[(0, 'Amazon'), (1, 'eBay'), (2, 'buyitdirect')])),
                ('url', models.TextField()),
            ],
            options={
                'ordering': ('price',),
            },
        ),
    ]
